module.exports = {
    credentials:"aws-credentials.json",
    bucketName:"trial-kendo-ch.com",
    patterns:[
	      "scripts/*.js",
	      "stylesheets/default.css",
	      "images/**/*.jpg",
	      "index.html",
	      "about.html",
        "error.html",
        "news/*.html",
        "play/*.html",
        "tournament/*.html",
        "common/**/*.scss",
        "common/**/*.css",
        "common/**/*.map",
        "common/**/*.png",
        "common/**/*.jpg",
        "common/**/*.js",
        "common/**/**/*.js",
        "common/**/**/**/*.css",
        "common/**/**/**/*.js"
    ]
}
